// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCotIdArg-T1mu9pjzhTAM2zgsN86aRGkw',
    appId: '1:19047311850:android:c32b09eda72639e5a5aa93',
    messagingSenderId: '19047311850',
    projectId: 'ecomm-app-39549',
    storageBucket: 'ecomm-app-39549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNBB3DeIKOaH2MxGsW7d-50fltMIkDt4',
    appId: '1:19047311850:ios:c88aa13cd7406593a5aa93',
    messagingSenderId: '19047311850',
    projectId: 'ecomm-app-39549',
    storageBucket: 'ecomm-app-39549.appspot.com',
    androidClientId: '19047311850-jseld29mmil1rovgv6s9u9r095m9ec9a.apps.googleusercontent.com',
    iosClientId: '19047311850-o4sqqdqpsaviakovi7lb4l8ks07pt154.apps.googleusercontent.com',
    iosBundleId: 'com.dbestech.learnTeacherBloc',
  );
}
